const APP_PREFIX = '@@PAGER'

// DOUBAN
export const DOUBAN_AUTH_REQUEST = `${APP_PREFIX}/DOUBAN/AUTH/REQUEST`
export const DOUBAN_AUTH_SUCCESS = `${APP_PREFIX}/DOUBAN/AUTH/SUCCESS`
export const DOUBAN_AUTH_FAILURE = `${APP_PREFIX}/DOUBAN/AUTH/FAILURE`

export const DOUBAN_STATUSES_REQUEST = `${APP_PREFIX}/DOUBAN/STATUSES/REQUEST`
export const DOUBAN_STATUSES_SUCCESS = `${APP_PREFIX}/DOUBAN/STATUSES/SUCCESS`
export const DOUBAN_STATUSES_FAILURE = `${APP_PREFIX}/DOUBAN/STATUSES/FAILURE`

// ZHIHU
export const ZHIHU_AUTH_REQUEST = `${APP_PREFIX}/ZHIHU/AUTH/REQUEST`
export const ZHIHU_AUTH_SUCCESS = `${APP_PREFIX}/ZHIHU/AUTH/SUCCESS`
export const ZHIHU_AUTH_FAILURE = `${APP_PREFIX}/ZHIHU/AUTH/FAILURE`

export const AUTH_STORE = `${APP_PREFIX}/AUTH/STORE`
export const AUTH_CLEAN = `${APP_PREFIX}/AUTH/CLEAN`
